PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Curriculums</relationshipLabel>
    <relationshipName>Curriculums</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Curriculum__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/Panel_Results__c.object-meta.xml
<CustomObject>
    <label>Panel Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Panel Results ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Panel_Results__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Panel Results</relationshipLabel>
    <relationshipName>Panel_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Panel Results</relationshipLabel>
    <relationshipName>Panel_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Technology__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipName>Technologies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TechDetails.cls
public with sharing class TechDetails {
    @auraenabled 
    public static List<Technology__c> alltech(){
        return [select name,Weight_in_Panel_Results__c from technology__c];
    }
    
    /*@auraenabled 
public static List<Technology__c> getCurriculumTechs(string curriculumId){

return [select name, Curriculum__c, Weight_in_Panel_Results__c from technology__c where Curriculum__c = :curriculumId];
}*/
    
    @auraenabled 
    public static list<Panel_Results__c> getCurriculumTechs(string curriculumId, string panelId){
        
        //send back a list of PanelResults objects that have the fields Grade, panelid, and techid
        list<Technology__c> techList = new list<Technology__c>();
        techList = [select name, Curriculum__c from technology__c where Curriculum__c = :curriculumId];
        integer techCount = [select count() 
                             from technology__c 
                             where Curriculum__c = :curriculumId];
        
        list<Panel_Results__c> panels = new list<Panel_Results__c>();
        
        for(integer i=0;i<techCount;i++){
            Panel_Results__c panelTechs = new Panel_Results__c();
            panelTechs.Technology__c = techlist[i].id;
            panelTechs.Panel__c = panelId;
            panelTechs.Grade__c = 00 ;
            panels.add(panelTechs);
        }
        
        insert panels;
        return panels;
    }
    
    @auraenabled
    //create a panel and send back the record ID
    public static id startPanel(string sentPanelName){
        Panel__c newPanel = new Panel__c();
        newPanel.name = sentPanelName;
        insert newPanel;
        return newPanel.id;
    }
    
    @auraenabled
    public static void submitPanel(list<Panel_Results__c> panelTech, list<string> gradeList){
        
        system.debug(panelTech);
        system.debug(gradeList);
        
        for(integer i = 0; i<panelTech.size(); i++){
            integer gradeInt = integer.valueOf(gradeList[i]);
            panelTech[i].Grade__c = gradeInt;
        }
        
        system.debug(panelTech);
        
        update panelTech;

    }
    
}