PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Curriculums</relationshipLabel>
    <relationshipName>Curriculums</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Curriculum__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/Panel_Results__c.object-meta.xml
<CustomObject>
    <label>Panel Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Panel Results ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Panel_Results__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Panel Results</relationshipLabel>
    <relationshipName>Panel_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Panel Results</relationshipLabel>
    <relationshipName>Panel_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Technology__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipName>Technologies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestPanelViewAPEXController.cls
@isTest
public class TestPanelViewAPEXController {
    @isTest
    public static void test(){
        // Negative testing
        List<Panel_Results__c> panelResultList = PanelViewAPEXController.getPanelResults('This is not an Id');
        System.assertEquals(0, panelResultList.Size());
        
        // Setting up minimal test data
        Curriculum__c currTest = new Curriculum__c();
        currTest.Name = 'Test Curriculum';
        insert currTest;
        
        Technology__c techTest = new Technology__c();
        techTest.Curriculum__c = currTest.Id;
        techTest.Name = 'Technology test';
        techTest.Weight_in_Panel_Results__c = 100;
        insert techTest;
        
        Panel__c panelTest = new Panel__c();
        panelTest.Name = 'This is the name of a random test panel';
        insert panelTest;
        
        Panel_Results__c panResTest = new Panel_Results__c();
        panResTest.Grade__c = 100;
        panResTest.Panel__c = panelTest.Id;
        panResTest.Technology__c = techTest.Id;
        insert panResTest;
        
        // Positive testing
        panelResultList = PanelViewAPEXController.getPanelResults(panelTest.Id);
        System.assertEquals(panResTest.Id, panelResultList[0].Id);
        
        // Negative testing
        panelResultList = PanelViewAPEXController.getPanelResults('This is not an Id');
        System.assertEquals(0, panelResultList.Size());
    }
}