PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Curriculums</relationshipLabel>
    <relationshipName>Curriculums</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Curriculum__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/Panel_Results__c.object-meta.xml
<CustomObject>
    <label>Panel Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Panel Results ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Panel_Results__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel_Results__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Panel Results</relationshipLabel>
    <relationshipName>Panel_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/fields/Repanel__c.field-meta.xml
<CustomField>
    <fullName>Repanel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Repanel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Panel_Results__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Panel Results</relationshipLabel>
    <relationshipName>Panel_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Technology__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipName>Technologies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestTechDetails.cls
@isTest
public class TestTechDetails {

    @isTest
    public static void testGetCurriculumTechs() {
        
        //Negative test, curriculum does not exist
        List<Technology__c> techList = TechDetails.getCurriculumTechs('not an id'); 
        System.assertEquals(0, techList.Size());
        
        //Insert test data, a curriculum and related technologies
        //First create a curriculum and insert to get an id 
        Curriculum__c curriculum = new Curriculum__c();
        curriculum.name = 'Salesforce';       
        insert curriculum;
        
		//Create a technology and relate it to the curriculum
		Technology__c technology = new Technology__c();
        technology.Name = 'Apex';
        technology.Weight_in_Panel_Results__c = 50;
        technology.Curriculum__c = curriculum.id;
        insert technology;        
        
        //Positive test
        techList = TechDetails.getCurriculumTechs(String.valueOf(curriculum.id));
        System.assertEquals(1, techList.Size());
        
    }
    
    @isTest
    public static void testStartPanelandPanelSubmit(){
        
        //Test if a panel object is inserted
        String panelId = TechDetails.startPanel('Test Panel');
        Panel__c panel = [SELECT Name FROM Panel__c WHERE Id = :panelId];
        System.assertEquals(Schema.Panel__c.SObjectType, panel.getSobjectType());        
        
        //Insert test data, a curriculum and related technologies
        //First create a curriculum and insert to get an id 
        Curriculum__c curriculum = new Curriculum__c();
        curriculum.name = 'Salesforce';       
        insert curriculum;
        
        //Create a list of technologies, relate them to curriculum then insert
        List<Technology__c> techList = new List<Technology__c>();
        for(Integer i=1;i<=4;i++){
            Technology__c technology = new Technology__c();
            technology.Name = 'Technology ' + i;
            technology.Weight_in_Panel_Results__c = 25;
            technology.Curriculum__c = curriculum.id;
        	techList.add(technology);
        }
		insert techList;
        
        //Create fake panel entries to pass into method
        //Method needs parameters:
        //(list<Technology__c> panelTech, list<string> gradeList, string panelId, list<string> commentList, list<boolean> repanelList)
        List<String> gradeList = new List<String> {'2','4','6','8'};
        List<String> commentList = new List<String> {'test','test','test','test'};
        List<Boolean> repanelList = new List<Boolean> {true,true,false,false};
            
        //Call method and test if insert succeeds
        TechDetails.submitPanel(techList, gradeList, panelId, commentList, repanelList);
        System.assert([SELECT Technology__c, Comment__c, Repanel__c, Grade__c FROM Panel_Results__c WHERE Panel__c = :panelId].Size()==4);
        
    }
    
}