paneltest1/force-app/main/default/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <label>Associate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Curriculums</relationshipLabel>
    <relationshipName>Curriculums</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Panel__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Curriculum__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Panel_Round__c.field-meta.xml
<CustomField>
    <fullName>Panel_Round__c</fullName>
    <label>Panel Round</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Panelist__c.field-meta.xml
<CustomField>
    <fullName>Panelist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panelist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PanelListViewAPEXController.cls
public  with sharing class PanelListViewAPEXController{
	@AuraEnabled
	public static List<Panel__c> doSearch(string nameOrId){
        List<Panel__c> results = new List<Panel__c>();
        try{
            results = [SELECT Id, Name, Associate__c, Curriculum__c, Panelist__c, Panel_Round__c FROM Panel__c Where Id = :nameOrId];
        }
        finally{
            if(results.isEmpty()){
                String searchStr = '%' + nameOrId + '%';
        		results =  [SELECT Id, Name, Associate__c, Curriculum__c, Panelist__c, Panel_Round__c FROM Panel__c Where Name LIKE :searchStr];
            }
        }
        return results;
    }
}